<?php
// $Id$

/**
 * Implementation of hook_install().
 */
function %title%_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function %title%_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE '%title%%%'");
}

// /**
//  * Implementation of hook_update_N()
//  */
// function %title%_update_6000() {
//   $ret = array();
//   $ret[] = array('success' => TRUE, 'query' => "Updated such and such.");
//   return $ret;
// }
